import React, {
  createContext,
  useContext,
  useState,
  useEffect,
  ReactNode,
} from "react";
import {
  IncidentReport,
  IncidentStatus,
  IncidentType,
  SeverityLevel,
} from "../types";
// import { MOCK_INCIDENTS } from '../constants';
import { db } from "../services/firebase";
import {
  collection,
  query,
  orderBy,
  limit,
  onSnapshot,
  setDoc,
  doc,
  updateDoc,
  where,
  Query,
  QuerySnapshot,
  DocumentData,
} from "firebase/firestore";

import { useAuth } from "./AuthContext";
import { addLog } from "../services/logService";

interface IncidentContextType {
  incidents: IncidentReport[];
  addReport: (report: IncidentReport) => Promise<void>;
  updateIncidentStatus: (id: string, status: IncidentStatus) => Promise<void>;
  stats: {
    total: number;
    resolved: number;
    critical: number;
    active: number;
  };
}

const IncidentContext = createContext<IncidentContextType | undefined>(
  undefined
);
export const IncidentProvider: React.FC<{ children: ReactNode }> = ({
  children,
}) => {
  const [incidents, setIncidents] = useState<IncidentReport[]>([]);
  const { user, role } = useAuth(); // Now valid because we swapped providers in App.tsx

  // Real-time listener from Firestore
  useEffect(() => {
    // If not authenticated, ensure incidents are cleared and do not subscribe
    if (!user) {
      console.log("🔒 No user authenticated - clearing incidents");
      setIncidents([]);
      return;
    }

    console.log(
      "📡 Authenticated! Starting Firestore listener for user:",
      user.uid,
      "Role:",
      role
    );

    let q: Query<DocumentData, DocumentData>;

    // Strict Data Isolation: Citizens see ONLY their own reports
    if (role === "citizen") {
      console.log("🔒 Citizen detected - Fetching only PERSONAL incidents");
      // we remove orderBy here to avoid needing a composite index (userId + timestamp)
      // We will sort client-side instead.
      q = query(collection(db, "incidents"), where("userId", "==", user.uid));
    } else {
      // Admins & Agencies see the most recent incidents.
      // Bounded read: never stream the whole collection to a client
      // (Phase 2 moves aggregate stats to a Cloud Function-maintained doc).
      q = query(
        collection(db, "incidents"),
        orderBy("timestamp", "desc"),
        limit(200)
      );
    }

    // Subscribe to updates
    const unsubscribe = onSnapshot(
      q,
      {
        includeMetadataChanges: false,
      },
      (snapshot: QuerySnapshot<DocumentData, DocumentData>) => {
        console.log(
          `📡 Firestore update received: ${snapshot.docs.length} incidents`
        );
        const liveIncidents: IncidentReport[] = [];
        snapshot.forEach((doc) => {
          liveIncidents.push({ id: doc.id, ...doc.data() } as IncidentReport);
        });
        // Ensure sorting by timestamp desc (client-side sort is cheap for this volume)
        liveIncidents.sort((a, b) => b.timestamp - a.timestamp);

        console.log(`✅ Setting ${liveIncidents.length} incidents to state`);
        setIncidents(liveIncidents);
      },
      (error) => {
        if (error.code === "permission-denied") {
          // Should happen less often now since we check !user
          console.log("🔒 Permission denied (likely logout)");
          setIncidents([]);
        } else {
          console.error("❌ Error fetching incidents:", error);
        }
      }
    );

    return () => {
      console.log("🔌 Unsubscribing from incidents listener");
      unsubscribe();
    };
  }, [user, role]); // Re-run when user changes (login/logout)

  const addReport = async (report: IncidentReport) => {
    try {
      console.log(`📝 Saving incident to Firestore:`, report.id);
      // We use setDoc to ensure the Document ID matches the Report ID generated by the client
      // or we could use addDoc and let Firestore generate it.
      // Here we trust the client ID for simplicity in this refactor.
      await setDoc(doc(db, "incidents", report.id), report);
      console.log(`✅ Incident saved successfully:`, report.id);
    } catch (error) {
      console.error("❌ Error adding report:", error);
      // alert("Failed to submit report. Please try again.");
      throw error; // Re-throw so caller knows it failed
    }
  };

  const updateIncidentStatus = async (id: string, status: IncidentStatus) => {
    try {
      const incidentRef = doc(db, "incidents", id);
      await updateDoc(incidentRef, { status });
      await addLog(
        "Status Update",
        `Changed Incident #${id.substring(0, 6)} to "${status}"`,
        role === "admin" ? "Admin" : role === "agency" ? "Agency" : "System",
        "edit"
      );
    } catch (error) {
      console.error("Error updating status:", error);
    }
  };

  const stats = {
    total: incidents.length,
    resolved: incidents.filter((i) => i.status === IncidentStatus.Resolved)
      .length,
    critical: incidents.filter((i) => i.severity === SeverityLevel.Critical)
      .length,
    active: incidents.filter((i) => i.status !== IncidentStatus.Resolved)
      .length,
  };

  return (
    <IncidentContext.Provider
      value={{ incidents, addReport, updateIncidentStatus, stats }}
    >
      {children}
    </IncidentContext.Provider>
  );
};

export const useIncidents = () => {
  const context = useContext(IncidentContext);
  if (!context)
    throw new Error("useIncidents must be used within an IncidentProvider");
  return context;
};
